file.uploadFolder: /home/goldenpg/upload
file.imageUrl: https://apiwx.bj-jbdpg.com/api/file/
spring:
  # 数据源
  datasource:
    url: jdbc:mysql://172.26.172.39:9612/xboot-test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: xboot
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果) 以下解密结果为123456
    password: xboot_center
    driverClassName: com.mysql.jdbc.Driver
  # Redis
  redis:
    host: 172.26.172.38
    password: redis.2019@Golden
    # 数据库索引 默认0
    database: 11
    port: 8611
    # 超时时间 Duration类型 3秒
    timeout: 3S